### ISSUE TITLE
isAutoPlay is not work.

### ISSUE THREAD

**Issue by zhaokgithub** [pepe19000/NgxVideoListPlayer#4]
For 'isAutoPlay ',I didn't set it.but the video is over it plays the next video automatically.

**Comment by pepe19000** [comment]
> For 'isAutoPlay ',I didn't set it.but the video is over it plays the next video automatically.

Please check now. I updated the package.

**Comment by zhaokgithub** [comment]
> > For 'isAutoPlay ',I didn't set it.but the video is over it plays the next video automatically.
> 
> Please check now. I updated the package.

It works arter I had updated the package. Thanks a lot.
