### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by devexpert9** [pepe19000/NgxVideoListPlayer#5]
Error: Module not found: Error: Can't resolve '@angular/cdk/layout' in '/Users/work/Documents/movemint/Fitness_Movemint/node_modules/ngx-video-list-player/fesm2020'

**Comment by pepe19000** [comment]
You have to install this package because NgxVideoListPlayer use BreakpointObserver from @angular/cdk/layout.

Just write this on cmd:
**npm install @angular/cdk --save**
